language: node_js
node_js: 'node'
addons:
  apt:
    packages:
    - libav-tools
before_deploy: ./build.bash
deploy:
  provider: pages
  local-dir: public
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
