# SPDX-FileCopyrightText: 2019 Tuomas Siipola
# SPDX-License-Identifier: GPL-3.0-or-later

language: node_js
node_js: 'node'
addons:
  apt:
    sources:
    - sourceline: 'ppa:mc3man/trusty-media'
    packages:
    - ffmpeg
script: npm run build
before_deploy:
  - npm install -g netlify-cli
  - cp _headers public
deploy:
  provider: script
  script: netlify deploy --dir=public --prod --message="$TRAVIS_COMMIT"
  skip_cleanup: true
  on:
    branch: master
