# SPDX-FileCopyrightText: 2019 Tuomas Siipola
# SPDX-License-Identifier: GPL-3.0-or-later

language: node_js
node_js: 'node'
dist: bionic
addons:
  apt:
    packages:
    - ffmpeg
script:
- npm test
- npm run build
