language: node_js
node_js: 'node'
addons:
  apt:
    sources:
    - sourceline: 'ppa:mc3man/trusty-media'
    packages:
    - ffmpeg
script: npm run build
before_deploy: npm install -g netlify-cli
deploy:
  provider: script
  script: netlify deploy --dir=public --prod
  skip_cleanup: true
  on:
    branch: master
